Added pessimistic locking append tests
YugaByte/jepsen pull request #91
Opened 2023-01-31 17:30 UTC by qvad

2023-02-01 14:54 UTC, frozenspider approved these changes
Accepted with comments

2023-02-01 14:54 UTC, frozenspider commented on yugabyte/src/yugabyte/auto.clj
> +  (if (contains? [:ysql/rc.pl.append
Maybe just ensure workload name contains `.pl.` ?

2023-02-01 14:54 UTC, frozenspider commented on yugabyte/src/yugabyte/ysql/append.clj
> +    (some-> conn
Not sure if this indentation change is in line with the style, probably not.

2023-02-03 18:04 UTC, robertsami requested changes

2023-02-03 18:04 UTC, robertsami commented on yugabyte/src/yugabyte/ysql/append.clj
> +(defn select-with-pessimistic
maybe more appropriate to call this `select-with-lock` as the clauses used here are available/valid even when wait-on-conflict behavior is disabled

2023-02-03 18:04 UTC, robertsami commented on yugabyte/src/yugabyte/ysql/append.clj
> +    (c/execute! conn [(select-with-pessimistic locking col table) v row]))
why do we need to do a select with lock before each update if we're testing wait-on-conflict concurrency control?

2023-02-03 18:04 UTC, robertsami commented on yugabyte/src/yugabyte/auto.clj
> +            (master-tserver-pessimistic-locking-flags test)
are we still running it /without/ wait on conflict?

also can we rename this `master-tserver-wait-on-conflict-flags`?

2023-02-03 21:35 UTC, robertsami approved these changes
LGTM once comments are addressed

2023-02-06 11:17 UTC, merged